# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4247232e965481fcaf699cb6db8b8cc3dbe0b86b751d716261a391d70562cb65f84b47e6eb29937e95bd5cdd81d55a0a5fbc5f9877710b780d745516e869e1a5

test:
  secret_key_base: 1e33eeb6ab8bf4a95872a1a8b81f0d089ec67711309724aacfeed6c0900e01b0400c52a8419906fb140532f12d19d60a2d3bff3049a9fb00deae428f4d35c30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
